config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root "keymaps#search"

  # SHORTNATE
  get "dashboard", :to => "users#dashboard"
  get "settings", :to => "users#settings"
  get "keymaps", :to => "keymaps#search"

  # DEVICES
  devise_for :users, controllers: {
            registrations: "users/registrations",
            sessions: "users/sessions",
          }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # USERS
  resources :users, only: %i[index show update destroy] do
    collection do
      get :dashboard
      get :settings
    end
  end

  # KEYMAPS
  resources :keymaps, only: %i[index show new edit create update destroy], shallow: true do
    resource :favorites, only: %i[create destroy]
    collection do
      get :search
      get :favorites
    end
  end

  # COMMANDS
  resources :commands, only: %i[create update destroy] do
    member do
      patch :recomend_update
    end
  end

  # FAVORITES
  resources :favorites, only: %i[create destroy]

  # RATES
  post "/rate" => "rater#create", :as => "rate"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/keymap.rb
class Keymap < ApplicationRecord

  # RATYRATE
  ratyrate_rateable "star"

  # RichText
  has_rich_text :content

  # acts-as-taggable-on
  acts_as_taggable

  # IMPRESSIONIST
  is_impressionable

  # ASSOCIATIONS
  belongs_to :user
  has_many :commands, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  # has_many :rates, dependent: :destroy
  has_many :inheritances, class_name: "inheritance", foreign_key: "inheritable_keymap_id", dependent: :destroy
  has_many :inheritances, class_name: "inheritance", foreign_key: "inheritancer_keymap_id", dependent: :destroy

  # ENUMS
  enum status: {
    "Public": 0,
    "Private": 1,
    "Draft": 2,
  }

  # INSTANCE-METHODS
  def favorite_by?(user)
      favorites.where(user_id: user.id).exists? if user.present?
  end

  def rating()
    (self.impressionist_count * 1) + (self.favorites.count * 128)
  end

  # RANSACKER FAVORITES
  ransacker :favorites_count do
    query = "(SELECT COUNT(favorites.keymap_id) FROM favorites where favorites.keymap_id = keymaps.id GROUP BY favorites.keymap_id)"
    Arel.sql(query)
  end

  # VALIDATES
  validates :user_id, presence: true
  validates :name,
            presence: true,
            length: { minimum: 2, maximum: 128 }
  validates :version, length: { maximum: 64 }
  validates :introduction, length: { maximum: 1000 }
  validates :status, presence: true
end

app/controllers/keymaps_controller.rb
class KeymapsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :authenticate_owner!, only: %i[edit update destroy]

  def authenticate_owner!
    return if current_user == Keymap.find(params[:id]).user
    flash[:danger] = "authenticate_owner!"
    redirect_back(fallback_location: root_path)
  end

  # PV COUNT BY IMPRESSIONIST
  impressionist :actions => %i[show]

  def index
  end

  def search
    keywords = params[:q]
    @q = Keymap.order(params[:sort]).ransack(keywords)
    @q.sorts = "updated_at desc" if @q.sorts.empty?
    @keymaps = @q.result(distinct: true).where(status: "Public")
  end

  def new
    @keymap = Keymap.new
  end

  def show
    @keymap = Keymap.find(params[:id])
    @categorized_keymap = @keymap.commands.group_by { |i| i.category_name }
  end

  def edit
    @keymap = Keymap.find(params[:id])
  end

  def create
    @keymap = current_user.keymaps.new(keymap_params)
    if @keymap.save
      redirect_to keymap_path(@keymap), success: "Successfully Created!"
    else
      flash[:danger] = "Save Error!"
      render :new
    end
  end

  def update
    @keymap = Keymap.find(params[:id])
    if @keymap.update(keymap_params)
      redirect_to keymap_path(@keymap), success: "Successfully Updated!"
    else
      flash[:danger] = "Save Error!"
      render :edit
    end
  end

  def destroy
    @keymap = Keymap.find(params[:id])
    @keymap.destroy
    redirect_to search_keymaps_path
  end

  def favorites
    @keymaps = current_user.favorite_keymaps.includes(:user).recent
  end

  private

  def keymap_params
    params.require(:keymap).permit(:name, :version, :introduction, :status, :tag_list, :content)
  end

  def search_params
    params.require(:q).permit(:name_cont)
  end
end

app/helpers/keymaps_helper.rb
module KeymapsHelper
end

app/views/keymaps/_edit_keymap.html.erb
<legend>Keymap</legend>
<%# NAME %>
<div class="form-group">
  <%= f.label :name, "Name *" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter keynmap name" %>
  <small id="nameHelp" class="form-text text-muted">Using strings of 64 characters max.</small>
</div>
<%# VERSION %>
<div class="form-group">
  <%= f.label :version, "Version" %>
  <%= f.text_field :version, class: "form-control", placeholder: "Enter keynmap version" %>
  <small id="versionHelp" class="form-text text-muted">using only alphanumeric characters.</small>
</div>
<%# TAG %>
<div class="form-group">
  <%= f.label :tag_list, "Tags" %>
  <div class="tags">
    <%= text_field_tag 'keymap[tag_list]', @keymap.tag_list.join(","), data: {role: "tagsinput"}, class: "form-control"%>
  </div>
</div>
<%# INTRODUCTION %>
<div class="form-group">
  <%= f.label :introduction, "Introduction" %>
  <%= f.text_area :introduction, class: "form-control", rows: "3", placeholder: "Enter keynmap introduction" %>
</div>
<%# STATUS %>
<fieldset class="form-group">
  <legend>Status</legend>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Public", class: "form-check-input", checked:true %>
      Public --- This keymap will be visible to everyone.
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Private", class: "form-check-input" %>
      Private
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Draft", class: "form-check-input" %>
      Draft
    </label>
  </div>
</fieldset>

app/views/keymaps/_favorite.html.erb
<% if not user_signed_in? %>
  <i class="fas fa-heart active-heart fa-lg"></i>
  <span class="ml-1 active-heart"><%= keymap.favorites.count %></span>
<% elsif keymap.favorite_by?(current_user) %>
  <div class="active-heart">
    <%= link_to keymap_favorites_path(keymap), method: :delete, id: :"js-favorite-button-for-keymap-#{keymap.id}" do %>
      <i class="fas fa-heart fa-lg"></i>
      <span><%= keymap.favorites.count %></span>
    <% end %>
  </div>
<% else %>
  <div class="inactive-heart">
    <%= link_to keymap_favorites_path(keymap), method: :post, id: :"js-favorite-button-for-keymap-#{keymap.id}" do %>
      <i class="fas fa-heart inactive-heart fa-lg"></i>
      <span><%= keymap.favorites.count %></span>
    <% end %>
  </div>
<% end %>

app/views/keymaps/_form.html.erb
<legend>Keymap</legend>
<%# NAME %>
<div class="form-group">
  <%= f.label :name, "Name *" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter keynmap name" %>
  <small id="nameHelp" class="form-text text-muted">Using strings of 64 characters max.</small>
</div>
<%# VERSION %>
<div class="form-group">
  <%= f.label :version, "Version" %>
  <%= f.text_field :version, class: "form-control", placeholder: "Enter keynmap version" %>
  <small id="versionHelp" class="form-text text-muted">using only alphanumeric characters.</small>
</div>
<%# TAG %>
<div class="form-group">
  <%= f.label :tag_list, "Tags" %>
  <div class="tags">
    <%= text_field_tag 'keymap[tag_list]', @keymap.tag_list.join(","), data: {role: "tagsinput"}, class: "form-control"%>
  </div>
</div>
<%# CONTENT %>
<div class="form-group">
  <%= f.label :content, "Note" %>
  <%= f.rich_text_area :content, class: "form-control-trix trix-content"%>
</div>
<%# STATUS %>
<fieldset class="form-group">
  <legend>Status</legend>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Private", class: "form-check-input" %>
      Private
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Public", class: "form-check-input", checked:true %>
      Public - This keymap will be visible to everyone.
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Draft", class: "form-check-input" %>
      Draft
    </label>
  </div>
</fieldset>

app/views/keymaps/_form_keymap.html.erb
<legend>Keymap</legend>
<%# NAME %>
<div class="form-group">
  <%= f.label :name, "Name *" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter keynmap name" %>
  <small id="nameHelp" class="form-text text-muted">Using strings of 64 characters max.</small>
</div>
<%# VERSION %>
<div class="form-group">
  <%= f.label :version, "Version" %>
  <%= f.text_field :version, class: "form-control", placeholder: "Enter keynmap version" %>
  <small id="versionHelp" class="form-text text-muted">using only alphanumeric characters.</small>
</div>
<%# TAG %>
<div class="form-group">
  <%= f.label :tag_list, "Tags" %>
  <div class="tags">
    <%= text_field_tag 'keymap[tag_list]', @keymap.tag_list.join(","), data: {role: "tagsinput"}, class: "form-control"%>
  </div>
</div>
<% if false %>
  <%# INTRODUCTION %>
  <div class="form-group">
    <%= f.label :introduction, "Introduction" %>
    <%= f.text_area :introduction, class: "form-control", rows: "3", placeholder: "Enter keynmap introduction" %>
  </div>
<% end %>
<%# CONTENT %>
<div class="form-group">
  <%= f.label :content, "Note" %>
  <%= f.rich_text_area :content, class: "form-control-trix trix-content"%>
</div>
<%# STATUS %>
<fieldset class="form-group">
  <legend>Status</legend>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Public", class: "form-check-input", checked:true %>
      Public --- This keymap will be visible to everyone.
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Private", class: "form-check-input" %>
      Private
    </label>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <%= f.radio_button :status, "Draft", class: "form-check-input" %>
      Draft
    </label>
  </div>
</fieldset>

app/views/keymaps/_keymap_list.html.erb
<% keymaps.each do |keymap| %>
  <%= link_to keymap_path(keymap), class: "list-group-item" do %>
    <li class="media">
      <div class="media-left hidden-xs">
        <img class="gravatar" src="">
        <%= image_tag (keymap.user.image_url(:small) || "#{asset_pack_path 'media/images/blank.png'}"), class: "border border-dark rounded user-image-md", fallback: "no_image.jpg" %>
      </div>
      <div class="media-body">
        <div class="row">
          <div class="col-md-5">
            <h4>
              <%= keymap.name %>
              <small>
                <%= keymap.version %>
              </small>
            </h4>
            <div>
              <%= keymap.introduction %>
            </div>
          </div>
          <div class="col-md-3">
            <span title="virtualbox">
              <span class="label label-inline label-outline">
                <%= keymap.tag_list %>
              </span>
              <span>
              </span></span></div>
          <div class="col-md-2">
            <div>
              Views
            </div>
            <div>
              <strong>
                <%= keymap.impressionist_count %>
              </strong>
            </div>
          </div>
          <div class="col-md-2">
            <div>
              Released
            </div>
            <div>
              <strong>
                <%= time_ago_in_words(keymap.updated_at) %> ago
              </strong>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
<% end%>

app/views/keymaps/_keymaps.html.erb
<% if keymaps.count == 0 %>
  <div class="row">
    <div class="col-12 text-center py-4">
      <h5 class="text-muted"><i class="fas fa-keyboard fa-lg"></i> There is no Keymaps.</h5>
    </div>
  </div>
<% end %>
<% keymaps.each do |keymap| %>
  <%= link_to keymap_path(keymap), class: "list-group-item" do %>
    <li class="media">
      <div class="media-left hidden-xs">
        <%= image_tag (keymap.user.image_url(:small) || "#{asset_pack_path 'media/images/blank.png'}"), class: "border border-dark rounded user-image-md", fallback: "no_image.jpg" %>
      </div>
      <div class="media-body">
        <span class="row">
          <div class="col-md-5">
            <h4>
              <%= keymap.name %>
              <small>
                <%= keymap.version %>
              </small>
            </h4>
            <div>
              <%= keymap.user.name.present? ? keymap.user.name : "@" + keymap.user.username %>
            </div>
          </div>
          <div class="col-md-3">
            <span class="label label-inline label-outline">
              <%= keymap.tag_list %>
            </span>
          </div>
          <div class="col-md-2">
            <div>
              <div class="active-heart">
                <i class="fas fa-heart fa-sm"></i>
                <span><%= keymap.favorites.count %></span>
              </div>
            </div>
            <div>
              <i class="fas fa-eye fa-sm"></i>
              <span class=""><%= keymap.impressionist_count(:filter=>:session_hash) %></span>
            </div>
          </div>
          <div class="col-md-2">
            <div>
              <strong>
                <%= time_ago_in_words(keymap.updated_at) %> ago
              </strong>
            </div>
          </div>
        </span>
      </div>
    </li>
  <% end %>
<% end%>

app/views/keymaps/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-info tag mr-1 mb-2"><%= tag %></span>
<% end %>

app/views/keymaps/_tags.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-info tag mr-1 mb-2"><%= tag %></span>
<% end %>

app/views/keymaps/edit.html.erb
<div class="row mt-4">
  <div class="col-sm-12">
    <h3>Edit Keymap</h3>
    <%# ERRORS %>
    <%= render 'layouts/errors', article: @keymap %>
    <%# FORMS %>
    <%= form_with scope: :keymap, url: keymap_path(@keymap), method: :put, local: true do |f| %>
      <fieldset>
        <%= render 'keymaps/form', f: f %>
        <%= f.button 'Save Changes', type: 'submit', onclick: 'submit()', id: 'customButton', class: "btn btn-primary"%>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/keymaps/index.html.erb
<h1>Keymaps#index</h1>
<p>Find me in app/views/keymaps/index.html.erb</p>
<%# TEMP %>
<div class="row mt-4">
  <div class="jumbotron m-3">
    <h1 class="display-4">Hello, Bootstrap!</h1>
    <hr class="my-4">
    <p>This is the template of Ruby on Rails using Bootstrap.</p>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
      <i class="far fa-window-maximize"></i>
      Click here
    </button>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="exampleModalLabel">Modal title</h6>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Hello!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/keymaps/new.html.erb
<%# KEYMAPS / NEW %>
<div class="row mt-4">
  <div class="col-12">
    <h3>New Keymap</h3>
    <%# DISPLAY ERROR %>
    <%= render 'layouts/errors', article: @keymap %>
    <%# FORM %>
    <%= form_with scope: :keymap, url: keymaps_path, method: :post, local: true do |f| %>
      <fieldset>
        <%= render 'keymaps/form', f: f %>
        <%= f.button 'Submit', type: 'submit', onclick: 'submit()', id: 'customButton', class: "btn btn-primary"%>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/keymaps/search.html.erb
<%# SEARCH FORM %>
<div class="row mt-4">
  <div class="col-12">
    <%= search_form_for @q, url: search_keymaps_path, local: true do |f| %>
      <fieldset class="col-12">
        <div class="form-group form-inline">
          <%= f.search_field :name_or_introduction_or_tags_name_cont_all, class: "form-control form-search col", placeholder: "Search" %>
          <%= button_tag :submit, class: "form-control form-search", style: "width:60px" do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>
<%# SORT BUTTONS %>
<div class="row">
  <div class="col-12">
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <%= sort_link(
            @q, :name, "Name",
            { default_order: :desc },
            { class: "sort_link btn btn-primary btn-sm" }
          ) %>
      <%= sort_link(
            @q, :favorites_count, "Favorites",
            { default_order: :desc },
            { class: "sort_link btn btn-primary btn-sm" }
          ) %>
      <%= sort_link(
            @q, :updated_at, "Released",
            { default_order: :desc },
            { class: "sort_link btn btn-primary  btn-sm" }
          ) %>
    </div>
  </div>
</div>
<%# KEYMAP LIST %>
<div class="row mt-2">
  <div class="col-12">
    <%= render 'keymaps/keymaps', keymaps: @keymaps %>
  </div>
</div>

app/views/keymaps/show.html.erb
<%# TITLES %>
<div class="row mt-3">
  <%# TITLE %>
  <h3 class="ml-1">
    <%= @keymap.name %>
  </h3>
  <div class="d-flex align-items-end col-sm ml-2 mb-3 mr-2 row">
    <div class="col">
      <%# - VERSION %>
      <span class="badge badge-primary mr-1"><%= @keymap.version %></span>
      <%# - STATUS %>
      <span class="badge badge-dark mr-2"><%= @keymap.status %></span>
    </div>
    <%# - PAGEVIEWS %>
    <div class="ml-2">
      <i class="fas fa-eye fa-lg"></i>
      <span class=""><%= @keymap.impressionist_count(:filter=>:session_hash) %></span>
    </div>
    <%# - FAVORITES %>
    <div class="ml-2">
      <%= render 'keymaps/favorite', keymap: @keymap %>
    </div>
    <%# - STAR %>
    <div class="ml-2">
      <%= rating_for @keymap, "star", disable_after_rate: false, enable_half: true %>
    </div>
  </div>
</div>
<%# DATES %>
<div class="row">
  <h6 class="ml-1">
    <span class="badge badge-dark"><%= time_ago_in_words(@keymap.updated_at) %> ago</span>
    <span class="badge badge-dark"> Created by <%= link_to @keymap.user.name.present? ? @keymap.user.name : "@" + @keymap.user.username, user_path(@keymap.user) %>
      when <%= @keymap.created_at.strftime("%d %B %Y, %R") %>
    </span>
  </h6>
</div>
<%# TAGS % %>
<div class="row">
  <div class="d-flex align-items-end ml-1 row">
    <%= render 'keymaps/tags', tag_list: @keymap.tag_list %>
  </div>
</div>
<%# CONTENT %>
<% if 1 < @keymap.content.to_plain_text.length %>
  <div class="row introduction">
    <div class="card text-white mt-2 mb-3" style="width:100%">
      <div class="card-body">
        <div class="card-text"><%= @keymap.content %></div>
      </div>
    </div>
  </div>
<% end %>
<%# KEYBOARD IMAGE %>
<%# <div class="row">
  <div class="keyboard">
  </div>
</div> %>
<%# ..KEYBOARD IMAGE %>
<%# SEARCH %>
<div class="row mt-4">
  <div class="col-12">
    <form action="#">
      <div class="form-group">
        <input type="text" name="search" value="" id="search" class="form-control form-search", placeholder="Search"/>
      </div>
    </form>
  </div>
</div>
<%# COMMANDS %>
<div class="row mt-2">
  <div class="col-12">
    <% @categorized_keymap.each do | key, value | %>
      <h5><%= key %></h5>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col" style="width:5%"></th>
            <th scope="col" style="width:40%">Command</th>
            <th scope="col" style="width:35%">Keybinding</th>
            <th scope="col" style="width:20%">When</th>
          </tr>
        </thead>
        <tbody>
          <% value.each do | command | %>
            <tr class="table-active">
              <td>
                <%# STAR %>
                <div id="request_ajax_update" >
                  <% if command.recomend %>
                    <%= link_to recomend_update_command_path(command), method: :patch, remote: true do %>
                      <i class="fas fa-star active-star"></i>
                    <% end %>
                  <% else %>
                    <%= link_to recomend_update_command_path(command), method: :patch, remote: true do %>
                      <i class="fas fa-star inactive-star"></i>
                    <% end %>
                  <% end %>
                </div>
              </td>
              <td><%= command.name %></td>
              <td><%= command.keybindings[0].name %></td>
              <td><%= command.when %></td>
              <% if user_signed_in? and command.keymap.user == current_user %>
                <td>
                  <%# TO DELETE %>
                  <%= link_to command_path(command), method: :delete, remote: true do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<% if current_user == @keymap.user %>
  <%# COMMAND IMPUT BUTTON - MODAL %>
  <div class="row">
    <div class="col-12 mt-3">
      <div class="text-center">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#commandImputModal">
          <i class="far fa-window-maximize"></i>
          New Keybind
        </button>
      </div>
    </div>
  </div>
  <%# COMMAND IMPUT FORM - MODAL %>
  <div class="modal fade bottom show" id="commandImputModal" tabindex="-1" role="dialog" aria-labelledby="commandImputModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-full-height modal-bottom" role="dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="commandImputModalLabel">New Keybind</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_with scope: :command, url: commands_path(keymap_id: @keymap.id), local: true do |form| %>
          <div class="modal-body">
            <div class="row form-group">
              <div class="col-sm-6 p-1">
                <%= form.text_field :name, class: "form-control", placeholder: "Name *   ex. Select All" %>
              </div>
              <div class="col-sm-6 p-1">
                <%= form.text_field :keybinding_name, class: "form-control", placeholder: "Keybinding *   ex. Cmd + A" %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6 p-1">
                <%= form.text_field :when, class: "form-control", placeholder: "When (optional)" %>
              </div>
              <div class="col-sm-6 p-1">
                <%= form.text_field :category_name, class: "form-control", placeholder: "Category (optional)" %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= form.button 'Submit', type: 'submit', onclick: 'submit()', id: 'customButton', class: "btn btn-primary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>