config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root "keymaps#search"

  # SHORTNATE
  get "dashboard", :to => "users#dashboard"
  get "settings", :to => "users#settings"
  get "keymaps", :to => "keymaps#search"

  # DEVICES
  devise_for :users, controllers: {
            registrations: "users/registrations",
            sessions: "users/sessions",
          }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # USERS
  resources :users, only: %i[index show update destroy] do
    collection do
      get :dashboard
      get :settings
    end
  end

  # KEYMAPS
  resources :keymaps, only: %i[index show new edit create update destroy], shallow: true do
    resource :favorites, only: %i[create destroy]
    collection do
      get :search
      get :favorites
    end
  end

  # COMMANDS
  resources :commands, only: %i[create update destroy] do
    member do
      patch :recomend_update
    end
  end

  # FAVORITES
  resources :favorites, only: %i[create destroy]

  # RATES
  post "/rate" => "rater#create", :as => "rate"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
    <% if article.errors.any? %>
  <div id="error_explanation" class="alert alert-danger p-4">
    <h4><%= article.errors.count %> errors prohibited this article from being saved:</h4>
    <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |flash_types, message| %>
  <div class="alert alert-<%= flash_types %> text-center py-2 px-4">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KEYPON</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="<%= asset_pack_path 'media/images/favicon.ico' %>">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
  </head>
  <body>
    <%# HEADER %>
    <header class="sticky-top">
      <nav class="navbar navbar-expand navbar-dark bg-dark">
        <%# LOGO %>
        <%= link_to keymaps_path do %>
          <div class="logo_area d-flex align-items-center">
            <div class="logo mx-auto">
            </div>
          </div>
        <% end %>
        <%# COLLAPSE BUTTON %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%# L MENU %>
        <div class="collapse navbar-collapse ml-2" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <%=  %>
            <li class="nav-item <%= is_active_controller_and_action?("users", "dashboard") %>">
              <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
            </li>
            <%# DISABLED YET %>
            <% if false %>
              <li class="nav-item <%= is_active_controller_and_action?("users", "index") %>">
                <a class="nav-link disabled" href="#">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Tags</a>
              </li>
            <% end %>
          </ul>
          <%# R MENU %>
          <% if user_signed_in? %>
            <%# + EDIT KEYMAP - MENU %>
            <ul class="navbar-nav">
              <% if is_active_controller_and_action?("keymaps", "show").present? %>
                <% if is_owner = current_user.id == Keymap.find(params[:id]).user.id %>
                  <li class="nav-item">
                    <%= link_to edit_keymap_path(@keymap), class: "nav-link" do %>
                      <i class="fas fa-edit fa-lg"></i>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
            <%# + NEW KEYMAP - MENU %>
            <ul class="navbar-nav">
              <%# + NEW KEYMAP - DROPDOWN MENU %>
              <% if is_active_controller_and_action?("keymaps", "new").present? %>
                <%# + NEW KEYMAP - NEW %>
              <% elsif is_active_controller_and_action?("keymaps", "show").present? %>
                <%# + NEW KEYMAP - KEYMAP %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-pen fa-lg"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" style="">
                    <%= link_to new_keymap_path, class: "dropdown-item nav-link" do %>
                      <i class="fas fa-plus" style="margin: 0 0.4rem "></i><span>Create New Keymap</span>
                    <% end %>
                    <%= link_to new_keymap_path, class: "dropdown-item nav-link" do %>
                      <i class="fas fa-plus" style="margin: 0 0.4rem "></i><span>Create New Keymap (Inharit)</span>
                    <% end %>
                  </div>
                </li>
              <% else %>
                <%# + NEW KEYMAP - COMMON %>
                <li class="nav-item">
                  <%= link_to new_keymap_path, class: "nav-link" do %>
                    <i class="fas fa-pen fa-lg"></i>
                  <% end %>
                </li>
              <% end %>
            </ul>
            <%# □ USER - DROPDOWN MENU %>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag (current_user.image_url(:small) || "#{asset_pack_path 'media/images/blank.png'}"), class: "border border-dark rounded user-image-sm"%>
                </a>
                <div class="dropdown-menu dropdown-menu-right" style="">
                  <%# □ USER - DASHBOARD %>
                  <%= link_to dashboard_path, class: "dropdown-item nav-link" do %>
                    <i class="fa fa-home" style="margin: 0 0.35rem "></i><span>Dashboard</span>
                  <% end %>
                  <%# □ USER - USER SETTINGS %>
                  <%= link_to settings_path, class: "dropdown-item nav-link" do %>
                    <i class="fa fa-cog" style="margin: 0 0.405rem "></i><span>User Settings</span>
                  <% end %>
                  <%# □ USER - SIGN OUT %>
                  <div class="dropdown-divider"></div>
                  <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item nav-link" do %>
                    <i class="fas fa-sign-out-alt" style="margin: 0 0.405rem "></i><span>Sign out</span>
                  <% end %>
                </div>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav mr-2">
              <li><%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %></li>
              <li><%= link_to "Log-in", new_user_session_path, class: "nav-link" %></li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <%# MAIN %>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%# FLASH MESSAGE %>
          <%= render partial: "layouts/flashes", flash: flash %>
        </div>
      </div>
    </div>
    <main>
      <%# CONTENTS %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%# FOOTER %>
    <footer class="my-5">
      <div class="text-center">
        <a class="btn btn-outline-info btn-sm opacity-65" href="https://twitter.com/craymaru">
          <small>© 2020 Cray, TT / KEYPON™ <i class="fab fa-twitter"></i></small>
        </a>
        <a class="btn btn-outline-success btn-sm opacity-65" href="https://github.com/craymaru/keypon">
          <small>GitHub <i class="fab fa-github-alt"></i></small>
        </a>
      </div>
    </footer>
  </body>
</html>